#!/bin/sh

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/keys ~/.config/sxhkd/sxhkdrc &
pgrep -x pipewire > /dev/null || pipewire &
pgrep -x pipewire-pulse > /dev/null || pipewire-pulse &
pgrep -x mpd > /dev/null || mpd &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
picom &
~/.fehbg &
~/.config/polybar/launch.sh --forest

# WM configs
bspc config automatic_scheme      alternate
bspc config border_width          0
bspc config window_gap            8
bspc config split_ratio           0
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Window rules
bspc rule -a VirtualBoxVM         desktop='^2' follow=on
bspc rule -a Transmission-gtk     desktop='^9'
bspc rule -a Zathura              state=tiled
#bspc rule -a Virt-manager         state=pseudo_tiled
bspc rule -a Gimp                 desktop='^8' state=floating follow=on
bspc rule -a mplayer2             state=floating
bspc rule -a Kupfer.py            focus=on
bspc rule -a Screenkey            manage=off
